services:
  web:
    build: .
    ports:
      - "3000:80"
    environment:
      - NODE_ENV=production
    volumes:
      - .:/app
      - ./node_modules:/app/node_modules
    env_file:
      - .env.production.local
