version: "3.8"

services:
  frontend:
    build:
      context: .
      args:
        REACT_APP_BASE_URL: ${REACT_APP_BASE_URL}
        REACT_APP_AUTH_URL: ${REACT_APP_AUTH_URL}
        REACT_APP_APP_URL: ${REACT_APP_APP_URL}
    container_name: movie-fe
    ports:
      - "80:80"
    env_file:
      - .env.production.local
    restart: always
